/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArranquesRouteImport } from './routes/arranques'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as CurvasRouteImport } from './routes/curvas'
import { Route as DocumentacionRouteImport } from './routes/documentacion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArranquesRoute = ArranquesRouteImport.update({
  id: '/arranques',
  path: '/arranques',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const CurvasRoute = CurvasRouteImport.update({
  id: '/curvas',
  path: '/curvas',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacionRoute = DocumentacionRouteImport.update({
  id: '/documentacion',
  path: '/documentacion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arranques': typeof ArranquesRoute
  '/creditos': typeof CreditosRoute
  '/curvas': typeof CurvasRoute
  '/documentacion': typeof DocumentacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arranques': typeof ArranquesRoute
  '/creditos': typeof CreditosRoute
  '/curvas': typeof CurvasRoute
  '/documentacion': typeof DocumentacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arranques': typeof ArranquesRoute
  '/creditos': typeof CreditosRoute
  '/curvas': typeof CurvasRoute
  '/documentacion': typeof DocumentacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arranques' | '/creditos' | '/curvas' | '/documentacion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arranques' | '/creditos' | '/curvas' | '/documentacion'
  id:
    '__root__' | '/' | '/arranques' | '/creditos' | '/curvas' | '/documentacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArranquesRoute: typeof ArranquesRoute
  CreditosRoute: typeof CreditosRoute
  CurvasRoute: typeof CurvasRoute
  DocumentacionRoute: typeof DocumentacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arranques': {
      id: '/arranques'
      path: '/arranques'
      fullPath: '/arranques'
      preLoaderRoute: typeof ArranquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curvas': {
      id: '/curvas'
      path: '/curvas'
      fullPath: '/curvas'
      preLoaderRoute: typeof CurvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacion': {
      id: '/documentacion'
      path: '/documentacion'
      fullPath: '/documentacion'
      preLoaderRoute: typeof DocumentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArranquesRoute: ArranquesRoute,
  CreditosRoute: CreditosRoute,
  CurvasRoute: CurvasRoute,
  DocumentacionRoute: DocumentacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
